const webpack = require('webpack');
const fs = require('fs');
const { merge } = require('@ris/utils');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const CaseSensitivePathsPlugin = require('case-sensitive-paths-webpack-plugin');

const webpackBaseConfig = require('./webpack.config.base');
const constant = require('./constant');

const plugins = [
  new webpack.HotModuleReplacementPlugin(), // Tell webpack we want hot reloading
  // Watcher doesn't work well if you mistype casing in a path so we use
  // a plugin that prints an error when you attempt to do this.
  // See https://github.com/facebook/create-react-app/issues/240
  new CaseSensitivePathsPlugin(),
];

if (fs.existsSync(constant.appEntryHtml)) {
  plugins.push(new HtmlWebpackPlugin({
    inject: true, // Inject all files that are generated by webpack, e.g. bundle.js
    template: constant.appEntryHtml,
  }));
}
module.exports = merge({
  mode: 'development',
  entry: constant.appEntry,
  output: {
    filename: '[name].js',
    chunkFilename: '[name].chunk.js',
    path: constant.appBuild,
    publicPath: '',
  },
  plugins,
  // Emit a source map for easier debugging
  // See https://webpack.js.org/configuration/devtool/#devtool
  devtool: 'eval-source-map',
  performance: {
    hints: false,
  },
}, webpackBaseConfig('development'));
